version: "2"

services:
  sslh:
    name: sslh
    image: pety3bi/sslh:latest
    ports:
      - 443:443

  mtproto:
    name: mtproto
    image: telegrammessenger/proxy:latest
    ports:
      - 443:443
    volumes:
      - proxy-config:/data

volumes:
  proxy-config:
